baseURL = 'https://albinshibyy.github.io/blog'
languageCode = 'en-us'
title = '@albinshibyy | Blog'
theme = 'hugo-blog-awesome'
defaultContentLanguage = 'en-gb'
enableEmoji = true
ignoreErrors = ['additional-script-loading-error']

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[Languages.en-gb]
languageName = 'English'
languageCode = 'en-gb'
contentDir = 'content/en'
weight = 1

[Languages.en-gb.menu]
[[Languages.en-gb.menu.main]]
pageRef = '/'
name = 'Home'
url = '/'
weight = 10
[[Languages.en-gb.menu.main]]
pageRef = 'posts'
name = 'Posts'
url = '/posts/'
weight = 20
[[Languages.en-gb.menu.main]]
pageRef = 'about'
name = 'About'
url = '/about/'
weight = 30

[Languages.en-gb.params]
sitename = 'Awesome hugo blog'
defaultColor = 'auto'
description = 'Minimal Hugo blog theme with light and dark mode support'
mainSections = ['posts']
toc = true
tocOpen = false
goToTop = true
additionalScripts = ['js/custom.js', 'js/custom-2.js']
dateFormat = ''
rssFeedDescription = 'summary'

[Languages.en-gb.params.author]
avatar = 'avatar.jpg'
intro = 'Welcome to my boring library'
name = 'Albin Shiby'
description = 'This my personal blog & everything i post here are only my personal views and blah blahh bla'

[Languages.en-gb.params.webmanifest]
name = 'sitename'
short_name = 'sitename'
start_url = '/'
theme_color = '#434648'
background_color = '#fff'
display = 'standalone'

[params.browserconfig]
TileColor = '#2d89ef'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/albinshibyy'

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/albinshibyy'

[[params.socialIcons]]
name = 'Rss'
url = '/index.xml'
